spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level:
    org.hibernate.stat: DEBUG