spring:
  application:
    name: patika-weather-project
  profiles:
    active: dev
  flyway:
    enabled: true

server:
  servlet:
    context-path: /api
    
openweather:
  base-url: https://api.openweathermap.org
  geo-path: /geo/1.0/direct
  air-pollution-path: /data/2.5/air_pollution
  api-key: ${OPENWEATHER_API_KEY}